### PR TITLE
move eventvideo div close

### PR DESCRIPTION
**Pull request by digital-gnome**
I think I did this.  eventVideo div wasn't properly wrapping everything.  Sorry.

### CODE REVIEW

**Comment by connortechnology** [comment]
I'm not sure this is right either.

**Comment by digital-gnome** [comment]
It's possible I copied wrong.  Something was a little strange before I
pushed.  I'll double check

**Comment by digital-gnome** [comment]
It's the same current zoneminder master.  It encloses everything except   if ($Event->SaveJPEGs() & 3).

**Comment by digital-gnome** [comment]
It doesn't really do anything that I can see but it either needs this fix or the opening tag needs to be in the video.js if block.  Currently it's a weird empty div above zms streams.

**Comment by digital-gnome** [comment]
Updated pull request.
It's used for the showStills button with the eventStills stuff.  I can't get that to trigger on mine but it hides eventVideo and imageFeed.  Currently all zoneminders with the h264 feature incorporated have this technically wrong but it doesn't really matter.  This makes it match what the javascript thought it looked like.

**Pull request merged**
