### PR TITLE
Filter page update/fixes

### PR DESCRIPTION
**Pull request by digital-gnome**
Filters in javascript for a more responsive page.  Also fixes form resubmit back button weirdness.  

Clicking filter from anywhere should pass any appropriate filter terms including limit and sort.  Limit and sort from filter page work again.  

Filter page centered and compressed.  Date/Time picker added.  I'm not sure why jscalendar wasn't included.  I used an addon for jquery-ui, MIT licensed.  I believe that is all ok with Debian.  We already had the jquery-ui js file, this adds the css and image files from it.

I think I tested every combination but I'm not sure.  This needs some testing I think.  Also limit defaults to 100 but prior to this it did not work so I'm not sure if we want that limit to apply.  1.31.1 does not have a default limit.

### CODE REVIEW

**Comment by digital-gnome** [comment]
Just had a chance to see the chosen update.  Will have to look at that some, probably shouldn't have different kinds of date pickers in different places.  Would still appreciate some testing to be sure I didn't miss any filter cases in the javascript.

**Comment by connortechnology** [comment]
chosen just does dropdowns so shouldn't interfere with date.

**Comment by digital-gnome** [comment]
Actually it's the datepicker.  Never realized you'd added one to montagereview.

**Comment by connortechnology** [comment]
Well that's just an html5 datetime input... and it is not well implemented in all browsers surprisingly.

**Comment by connortechnology** [comment]
What's with the ui icons?  We already have the ones that come with bootstrap

**Comment by digital-gnome** [comment]
2 reasons.  It's part of jquery-ui and the addon was complaining about missing icons.  The main reason is I didn't know we had any icons with bootstrap.  I can't find them, guess I'll have to research bootstrap some.

**Comment by digital-gnome** [comment]
I changed it to use the bootstrap icons in the picker.  

Added chosen to most of the dropdowns, I can't get it to work well with the bracket boxes.  Either they're too small and confusing due to wrapping or I have to explicitly set a width large enough for everything to fit.  I'll either have to set the width inline with javascipt or just leave them as regular dropdowns.  Chosen isn't really needed for those but I hate that it doesn't look consistent.

**Comment by connortechnology** [comment]
Most drop downs don't need to be chosen. It would be nice to style the rest to look like them though. Maybe you should just steal the styling for regular drop-down

On December 17, 2017 9:19:12 AM EST, digital-gnome <notifications@github.com> wrote:
>I changed it to use the bootstrap icons in the picker.  
>
>Added chosen to most of the dropdowns, I can't get it to work well with
>the bracket boxes.  Either they're too small and confusing due to
>wrapping or I have to explicitly set a width large enough for
>everything to fit.  I'll either have to set the width inline with
>javascipt or just leave them as regular dropdowns.  Chosen isn't really
>needed for those but I hate that it doesn't look consistent.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/connortechnology/ZoneMinder/pull/67#issuecomment-352258867

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by digital-gnome** [comment]
Removed chosen from conjuction and brackets.  Restyled dropdowns to match chosen on filters page.

**Comment by connortechnology** [comment]
#72

**Pull request merged**
