### PR TITLE
Ui tweaks for storage areas 

### PR DESCRIPTION
**Pull request by pliablepixels**
#88 

This will always be the latest screenshot showing progress (will be updated)

login:
screen shot 2018-03-25 at 4 21 27 pm

console:
screen shot 2018-03-25 at 11 44 11 am

log:
screen shot 2018-03-26 at 11 08 23 am

### CODE REVIEW

**Comment by connortechnology** [comment]
Ok, let me know when you are comfortable with me merging.  I love it so far.

**Comment by pliablepixels** [comment]
ok cool, feel free to merge it anytime I can always do a new PR when I work on something else - my understanding is once you merge it, I can't keep pushing right?

But please undo/re-do whatever you don't like/want and please give it a test first so I know I've checked in everything. The screenshot at the top is what it should look like .If not, I've missed some files.

**Comment by connortechnology** [comment]
I think if I merge, the PR gets closed, but of course your branch lives on, and you can make another PR.. I just mean let me know when you think you've reach a point of stability and want me to merge it.  Bascially when you are happy with it.   

I will comment as I feel necessary.

**Comment by pliablepixels** [comment]
Oh. Well ok if I can keep pushing on my branch fine. Whatever I am pushing is tested on chrome and safari so merge as you see fit but please run it first so I know I’ve not missed a file.

**Pull request merged**
